//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToysStoreApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToyStoreEntities : DbContext
    {
        private static ToyStoreEntities _context;
        public ToyStoreEntities()
            : base("name=ToyStoreEntities")
        {
        }

        public static ToyStoreEntities GetContext()
        {
            if (_context == null)
                _context = new ToyStoreEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<HistoryOfEnter> HistoryOfEnter { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<PersonalOffer> PersonalOffer { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfUser> TypeOfUser { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
